name: Sync Fork

on:
  workflow_dispatch:
  schedule: 
  # mm HH DD MM DW
  - cron: "0 13 * * *"
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'andreastind'
          git config --global user.email 'andreastind@users.noreply.github.com'
          
          # "git checkout main" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be unstructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://github.com/AU-DIS/dm2023-exercises.git
          git fetch upstream
          
          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          #git checkout -b feature/x origin/feature/x
          #git merge --no-edit upstream/feature/x
          #git push origin feature/x
          
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
